package hu.csega.toolshed.parser.preprocessor.impl;

public enum PreProcessorState {

	INIT,
	UNPROCESSED,
	STRINGS_AND_COMMENTS_IDENTIFIED,
	WHITESPACES_IDENTIFIED,
	STANDALONE_OPERATORS_IDENTIFIED,
	OPERATOR_SEQUENCES_IDENTIFIED,
	UNPROCESSED_EXPRESSIONS_TRANSFORMED,
	IGNORABLE_EXPRESSIONS_DROPPED,
	VALIDATED

}
